"""
Maintains progress.json and regenerates the README dashboard.
Tracks solved counts by difficulty and pattern.
"""

import json
from pathlib import Path
from datetime import date
from collections import defaultdict

PROGRESS_FILE = Path("progress.json")

DIFFICULTY_ORDER = ["Easy", "Medium", "Hard"]

README_TEMPLATE = """\
# GitLeetNotes — My LeetCode Study Journal

> Auto-generated by [GitLeetNotes](https://github.com/aqn96/gitleetnotes). \\
> Every accepted solution becomes a structured study note — pattern, complexity, and key insight included.

## Progress Overview

| Difficulty | Solved |
|---|---|
{difficulty_rows}

**Total: {total} problems solved**

## Patterns Covered

{pattern_table}

## Recent Solutions

{recent_table}

---
*Last updated: {last_updated}*
"""


def load_progress(path: Path = PROGRESS_FILE) -> dict:
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {"solved": {}, "by_difficulty": {}, "by_pattern": {}}


def save_progress(data: dict, path: Path = PROGRESS_FILE) -> None:
    path.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")


def record_solution(
    progress: dict,
    submission_id: str,
    problem_id: str,
    title: str,
    slug: str,
    difficulty: str,
    pattern: str,
    note_path: str,
    solved_on: str,
    lang: str = "",
) -> bool:
    """
    Adds a solution to the progress dict.
    Returns True if it was new, False if already recorded.
    """
    if submission_id in progress["solved"]:
        return False

    progress["solved"][submission_id] = {
        "problem_id": problem_id,
        "title": title,
        "slug": slug,
        "difficulty": difficulty,
        "pattern": pattern,
        "lang": lang,
        "note_path": note_path,
        "solved_on": solved_on,
    }

    progress.setdefault("by_difficulty", {})
    progress["by_difficulty"][difficulty] = (
        progress["by_difficulty"].get(difficulty, 0) + 1
    )

    progress.setdefault("by_pattern", {})
    progress["by_pattern"][pattern] = (
        progress["by_pattern"].get(pattern, 0) + 1
    )

    return True


def _progress_bar(count: int, total: int, width: int = 20) -> str:
    if total == 0:
        return "░" * width
    filled = round(count / total * width)
    return "█" * filled + "░" * (width - filled)


def generate_readme(progress: dict) -> str:
    by_diff = progress.get("by_difficulty", {})
    by_pattern = progress.get("by_pattern", {})
    solved = progress.get("solved", {})
    total = sum(by_diff.values())

    # Difficulty rows
    diff_rows = "\n".join(
        f"| {d} | {by_diff.get(d, 0)} |"
        for d in DIFFICULTY_ORDER
    )

    # Pattern table with progress bars
    pattern_lines = ["| Pattern | Count | Progress |", "|---|---|---|"]
    pattern_total = sum(by_pattern.values()) or 1
    for pattern, count in sorted(by_pattern.items(), key=lambda x: -x[1]):
        bar = _progress_bar(count, pattern_total)
        pattern_lines.append(f"| {pattern} | {count} | `{bar}` |")
    pattern_table = "\n".join(pattern_lines)

    # Recent 10 solutions
    recent = sorted(solved.values(), key=lambda x: x["solved_on"], reverse=True)[:10]
    recent_lines = [
        "| # | Problem | Difficulty | Pattern | Date |",
        "|---|---|---|---|---|",
    ]
    for s in recent:
        link = f"[{s['title']}]({s['note_path']})"
        recent_lines.append(
            f"| {s['problem_id']} | {link} | {s['difficulty']} | {s['pattern']} | {s['solved_on']} |"
        )
    recent_table = "\n".join(recent_lines)

    return README_TEMPLATE.format(
        difficulty_rows=diff_rows,
        total=total,
        pattern_table=pattern_table,
        recent_table=recent_table,
        last_updated=date.today().isoformat(),
    )
